In [17]:
# 4)Create a 4x4 NumPy array filled with random integers between 1 and 100. 
# Then, reshape this array into two separate 2D arrays, where one represents the rows 
# and the other represents the columns. Write a function, 
# preferably using a lambda function, to calculate the sum of each row and each column separately, 
# and return the results as two separate NumPy arrays

import numpy as np

arr = np.random.randint(1, 101, (4, 4))
arr

array([[51, 95, 95, 59],
       [23, 17,  5, 42],
       [16,  8, 59, 51],
       [45,  2, 47, 76]])

In [18]:
arr_row = arr.reshape(4,4)
arr_row

array([[51, 95, 95, 59],
       [23, 17,  5, 42],
       [16,  8, 59, 51],
       [45,  2, 47, 76]])

In [19]:
arr_col = arr.T.reshape(4,4)
arr_col

array([[51, 23, 16, 45],
       [95, 17,  8,  2],
       [95,  5, 59, 47],
       [59, 42, 51, 76]])

In [20]:
sum_rows = np.apply_along_axis(lambda x: np.sum(x), axis=1, arr=arr_row)
sum_rows

array([300,  87, 134, 170])

In [21]:
sum_columns = np.apply_along_axis(lambda x: np.sum(x), axis=1, arr=arr_col)
sum_columns

array([135, 122, 206, 228])